force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <description>Object to store help desk tickets (training requests, user management, and other requests) submitted by users on the platform.</description>
    <label>Ticket</label>
    <nameField>
        <displayFormat>Ticket-{0000}</displayFormat>
        <label>Ticket Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/fields/ContactName__c.field-meta.xml
<CustomField>
    <fullName>ContactName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Who should our team contact regarding this ticket?</description>
    <inlineHelpText>Who is this ticket assigned to?</inlineHelpText>
    <label>Contact Name</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipName>Help Desk Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <description>Add summary details for the ticket. For example: record error, feature request, etc.</description>
    <inlineHelpText>Add summary details for the ticket. For example: record error, feature request, etc.</inlineHelpText>
    <label>Details</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/ExpectedOutcome__c.field-meta.xml
<CustomField>
    <fullName>ExpectedOutcome__c</fullName>
    <description>What outcome is expected as a result of this change?</description>
    <inlineHelpText>What was the outcome that you expect as a result of this change?</inlineHelpText>
    <label>Expected Outcome</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>What is the priority level for this ticket? This will help our team respond appropriately.</description>
    <inlineHelpText>What is the priority level for this ticket? This will help our team respond appropriately.</inlineHelpText>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
                <default>true</default>
                <label>Low</label>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Critical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/ReportedObject__c.field-meta.xml
<CustomField>
    <fullName>ReportedObject__c</fullName>
    <description>Which object is this issue related to?</description>
    <inlineHelpText>Which object is this issue related to?</inlineHelpText>
    <label>Reported Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/ReportedRecord__c.field-meta.xml
<CustomField>
    <fullName>ReportedRecord__c</fullName>
    <description>What record is this issue related to?</description>
    <inlineHelpText>What record is this issue related to?</inlineHelpText>
    <label>Reported Record</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/StepstoReproduce__c.field-meta.xml
<CustomField>
    <fullName>StepstoReproduce__c</fullName>
    <description>Steps for our team to reproduce the issue.</description>
    <inlineHelpText>How can our team reproduce the issue?</inlineHelpText>
    <label>Steps to Reproduce</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>What is the nature of this issue?</description>
    <inlineHelpText>What is the nature of this issue?</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User Creation or Deactivation</fullName>
                <default>true</default>
                <label>User Creation or Deactivation</label>
            </value>
            <value>
                <fullName>Question</fullName>
            </value>
            <value>
                <fullName>Feature Request</fullName>
            </value>
            <value>
                <fullName>Training Request</fullName>
            </value>
            <value>
                <fullName>Record or Object Issue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HelpDesk.cls
/**
 * @description       : 
 * @author            : brandon@flavorman.com
 * @group             : 
 * @last modified on  : 02-05-2022
 * @last modified by  : brandon@flavorman.com
**/
public with sharing class HelpDesk {
     @AuraEnabled (cacheable = true)
    /**
     * Return list of tickets; result will be paginated so records will be sent based on calculation of pageNumber and pageSize
     * totalrecords is NOT used but we pass it so we can refresh Wire method on lwc size when this changes
     * 
     * This method is cached because it's used in wire
     */
    public static List<Ticket__c> getTicketList(Integer pageNumber, Integer pageSize, Integer totalRecords) {
        List<Ticket__c> ticketList = new List<Ticket__c>(); 

        try{
            Integer offset = (pageSize * (pageNumber - 1));
            ticketList = [SELECT 
                    ID, Name, Details__c, ExpectedOutcome__c, Priority__c, ReportedObject__c,
                    ReportedRecord__c, StepstoReproduce__c, Type__c, Department__c, AssignedTo__c, ContactName__c, AssignedTo__r.Name
                    FROM Ticket__c WITH SECURITY_ENFORCED
                    ORDER BY Name DESC
                    limit :pageSize OFFSET :offset
                ];
        }catch(Exception e){ Util.log('HelpDesk:getTicketList():Exception' + e.getMessage());}
        return ticketList;
    }
	/**
	 * Return total ticket records
	 * This count will be used for pagination
     * 
     * This method is cached because it's used in wire
	 */
    @AuraEnabled (cacheable = true)
    public static Integer getTicketCount() {  
        Integer count = 0;
        try{
            count = [SELECT count()  FROM Ticket__c WITH SECURITY_ENFORCED];
        }catch(Exception e){ Util.log('HelpDesk:getTicketList():Exception' + e.getMessage());}
        return count; 
    } 
}